spring:
    profiles:
        active: dev
    datasource:
        url: jdbc:postgresql://localhost:5432/wallet
        username: postgres
        password: 12345
    jpa:
        hibernate:
            ddl-auto: none
    properties:
        hibernate:
            show_sql: true
            use_sql_comments: true
            format_sql: true
            type: trace